# Generated by Django 4.2.3 on 2023-07-06 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Deepthought',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
